safe:        false
baseurl:     /

name: Ivan Santos' Blog
description: Ivan Santo's Blog
url: http://ivansjr.com.br

source:      .
destination: ./_site
plugins_dir:     ./_plugins
paginate_path: 'blog/page:num'

future:      true
lsi:         false
markdown:    redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile
permalink:   /:title/
paginate: 30


redcarpet:
  extensions: []


name: Ivan Santos
highlighter: pygments

gems: ['jekyll-paginate']


# #Permalink
# permalink: /:categories/:title

excerpt_separator: "<!-- more -->"

#Exclude
exclude: [".rvmrc", ".ruby-version", ".ruby-gemset", "README.md",
  "Rakefile", "changelog.md", "*.scss", "sandbox",
  "node_modules", "Gruntfile.js", "bootstrap", "_site_git", "config.rb"

  ]
